spring:
  datasource:
    username: dbuser
    password: '{cipher}AQAcaQa/QmxiLMB7ZhwQw0lYqSs+Zn1dp9bWzbxCXPrfeEO++dyWgeayWYMQ+WiOpWW1G37ZBn54sFvWW5NEOeykUzUJl/P1mWUrzupzRQJAao88Yfq3GQlGOgElwFyN4qn7c0XkGLJwLJATs4JYLuVxIg3KOddTpWfCwarvnDQM73OcDQwCGrBP5nAdx+s3/Q+epRaYKGWuy3GcE2jqX221uNIc0zIfK8re7lB0lgu3sRIAZPDK8rUc3SfWnzgeIqV6LPIW55T5sCyUCMRhpuTrkiY50dpxnC+SEwG6Dzmkw2uzzblyEvJYRF4UQW4xVfI7JXV2AvU1b7ZkpyPxcrzktUvkYG6o0dZSGvRHxU7rAFiBO64vMBC9jZWWBtLLrOE='
