spring:
  datasource:
  username: dbuser
    password: 'AQBUKyvzDotumoHOvl8z1oc3UPXYyvY+eUlonrB8SlfQboiCbLcmoE4jU0OKvkzWaqK/UJQjFPE3NppGJZoBDLx3XEJ2FE+sJM18Ia9KBrn1FrAH3Ux2vupTemjhxWhGSnrIlYJihHs03N6/79iJLFTwqph/vHm5HM0f8BhsWzr7d0ghD76c/xYrh3rS/pQfZCtRsw8MJYkShYFLSN2ZmSA4qUuLaaoznYd5CesOat9N5bRuE1ECBe3xZEA+G41csHuw/7QBRmf8J8hyMWrWInFFJf08oy5anOdcs62nS4gyrE1QUnkoVv0uDpIQzDCmya7/bysqjLY7d3lN4JUR4BsmgQ9SMPMedIQwO83c//LFjJfoMb3Ld/WZ2GfBB2WnabY='
